pipeline {
    agent any

    tools {
        nodejs '10.12.0'
    }

    environment {
        API_USER = 'api-user'
        APP_NAME = 'devopsoh/api-user'
        ACR_HOST = 'openhacktce4acr.azurecr.io'
        SRC_DIR = 'apis/userprofile'
        IMG_TAG = "${env.BUILD_TAG}"
        API_URL = "akstraefikopenhacktce4.australiaeast.cloudapp.azure.com"
    }

    stages{
        stage('Code Test') {
            steps {
                dir("${env.SRC_DIR}") {
                    sh '''
                        npm install
                        npm test
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${env.SRC_DIR}") {
                    script {
                        docker.build("${env.ACR_HOST}/${env.APP_NAME}:${env.IMG_TAG}")
                    }
                }
            }
        }

        stage('Upload Docker Image to ACR') {
            steps {
                script {
                    withDockerRegistry(credentialsId: '162a5f2f-bc39-4c82-a67b-7b9eedb3afe4', url: "https://${env.ACR_HOST}") {
                        
                        docker.image("${env.ACR_HOST}/${env.APP_NAME}:${env.IMG_TAG}").push("${env.IMG_TAG}")
                    }
                }
            }
        }

        stage('Helm Deploy') {
            steps {
                dir("${env.SRC_DIR}") {
                    sh '''
                        IMAGE = "${env.ACR_HOST}/${env.APP_NAME}"
                        TAG = "${env.IMG_TAG}"
                        installPath = "${WORKSPACE}/apis/userprofile/helm"
                        BaseUri = "http://${env.API_URL}"
                        dnsUrl = "${env.API_URL}"
                        helm upgrade --install ${env.API_USER} $installPath --set repository.image=$IMAGE,repository.tag=$TAG,env.webServerBaseUri=$BaseUri,ingress.rules.endpoint.host=$dnsUrl
                    '''
                }
            }
        }

    }
}