pipeline {
    agent any

    environment {
        APP_NAME = 'UserJava'
        SRC_DIR = 'apis/user-java'
    }

    stages{
        stage('Build Docker Image') {
            steps {
                dir("${env.SRC_DIR}") {
                    script {
                        docker.build("UserJava:${env.BUILD_ID}")
                    }
                }
            }
        }
    }
}